/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporteshirata.GUI;

import com.mycompany.transporteshirata.Datos.MantenimientoDao;
import com.mycompany.transporteshirata.Logica.Mantenimiento;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pccas
 */
public class GuiHistorialMantenimiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiHistorialMantenimiento
     */
    public GuiHistorialMantenimiento() {
        initComponents();
        cargarTabla("");
    }

    public void cargarTabla(String filtroPatente) {
        String col[] = {"ID Mantenimiento", "Fecha", "Tipo", "Descripción", "Km. Mantenimiento", "Patente Camión"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        MantenimientoDao mDao = new MantenimientoDao();

        List<Mantenimiento> lista = mDao.listarMantenimientos();

        for (Mantenimiento m : lista) {
            
            if (filtroPatente == null || filtroPatente.isEmpty()
                    || m.getCamion().getPatente().toLowerCase().contains(filtroPatente.toLowerCase())) {

                Object[] objs = {
                    m.getIdMantenimiento(),
                    m.getFecha(),
                    m.getTipo(),
                    m.getDescripcion(),
                    m.getKilometrajeMantenimiento(),
                    m.getCamion().getPatente()
                };
                tableModel.addRow(objs);
            }
        }
        tbl_historial.setModel(tableModel);
    }

    public void limpiarCajas() {
        txt_id.setText("");
        txt_camion.setText("");
        txt_fecha.setText("");
        txt_kilometraje.setText("");
        txt_descripcion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_historial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        bt_buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bt_refrescar = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_kilometraje = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        txt_camion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmb_tipo = new javax.swing.JComboBox<>();
        bt_editar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_desc = new javax.swing.JTextField();

        setClosable(true);

        tbl_historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_historialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_historial);

        jLabel1.setText("Buscar por patente");

        bt_buscar.setText("Buscar");
        bt_buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_buscar.addActionListener(this::bt_buscarActionPerformed);

        jLabel2.setText("ID");

        bt_refrescar.setText("Ver Todos");
        bt_refrescar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_refrescar.addActionListener(this::bt_refrescarActionPerformed);

        txt_id.setEditable(false);
        txt_id.addActionListener(this::txt_idActionPerformed);

        jLabel3.setText("Patente");

        jLabel4.setText("Fecha");

        jLabel5.setText("Kilometraje Mantenimiento");

        txt_fecha.setEditable(false);

        txt_camion.setEditable(false);

        jLabel6.setText("Descripción");

        jLabel7.setText("Tipo");

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preventivo", "Correctivo", " " }));

        bt_editar.setText("Guardar Cambios");
        bt_editar.addActionListener(this::bt_editarActionPerformed);

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(this::bt_eliminarActionPerformed);

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(this::bt_cancelarActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Descripcion");

        txt_desc.setBackground(new java.awt.Color(204, 255, 255));
        txt_desc.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        txt_desc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_desc.setToolTipText("");
        txt_desc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_desc.addActionListener(this::txt_descActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(76, 76, 76))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bt_editar)
                                            .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt_eliminar)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_cancelar)
                                        .addGap(49, 49, 49)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(44, 44, 44)
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_camion))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(24, 24, 24)
                                            .addComponent(txt_fecha))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(bt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(bt_refrescar)
                                                    .addGap(0, 0, Short.MAX_VALUE))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_desc))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_buscar)
                    .addComponent(bt_refrescar))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_camion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cancelar)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_desc))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void tbl_historialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_historialMouseClicked
        int fila = tbl_historial.getSelectedRow();
        if (fila != -1) {
            txt_id.setText(tbl_historial.getValueAt(fila, 0).toString());
            txt_fecha.setText(tbl_historial.getValueAt(fila, 1).toString());
            cmb_tipo.setSelectedItem(tbl_historial.getValueAt(fila, 2).toString());
            txt_descripcion.setText(tbl_historial.getValueAt(fila, 3).toString());
            txt_desc.setText(tbl_historial.getValueAt(fila, 3).toString());
            txt_kilometraje.setText(tbl_historial.getValueAt(fila, 4).toString());
            txt_camion.setText(tbl_historial.getValueAt(fila, 5).toString());
        }
    }//GEN-LAST:event_tbl_historialMouseClicked

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        String patente = txt_buscar.getText();
        cargarTabla(patente);
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refrescarActionPerformed
        txt_buscar.setText("");
        cargarTabla("");
        limpiarCajas();
    }//GEN-LAST:event_bt_refrescarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        if (txt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla para editar.");
            return;
        }
        try {
            
            Mantenimiento m = new Mantenimiento();
            m.setIdMantenimiento(Integer.parseInt(txt_id.getText()));
            m.setFecha(LocalDate.parse(txt_fecha.getText()));
            m.setTipo(cmb_tipo.getSelectedItem().toString());
            m.setDescripcion(txt_descripcion.getText());
            m.setKilometrajeMantenimiento(Integer.parseInt(txt_kilometraje.getText()));

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en los datos. Revise el formato.");
        }
        Mantenimiento m = new Mantenimiento();
        m.setIdMantenimiento(Integer.parseInt(txt_id.getText()));
        m.setFecha(LocalDate.parse(txt_fecha.getText()));
        m.setTipo(cmb_tipo.getSelectedItem().toString());
        m.setDescripcion(txt_descripcion.getText());
        m.setKilometrajeMantenimiento(Integer.parseInt(txt_kilometraje.getText()));

        MantenimientoDao mDao = new MantenimientoDao();
        if (mDao.modificarDetallesMantenimiento(m)) {
            JOptionPane.showMessageDialog(this, "✅ Registro actualizado correctamente.");
            cargarTabla(txt_buscar.getText()); 
            limpiarCajas();
        }
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        if (txt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla para eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este registro histórico?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            MantenimientoDao mDao = new MantenimientoDao();
            int id = Integer.parseInt(txt_id.getText());
            if (mDao.eliminarMantenimiento(id)) {
                JOptionPane.showMessageDialog(this, "✅ Registro eliminado.");
                cargarTabla(txt_buscar.getText());
                limpiarCajas();
            }
        }
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        limpiarCajas();
        tbl_historial.clearSelection();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void txt_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_refrescar;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_historial;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_camion;
    private javax.swing.JTextField txt_desc;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_kilometraje;
    // End of variables declaration//GEN-END:variables
}
