/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporteshirata.GUI;

import com.mycompany.transporteshirata.Datos.CamionDao;
import com.mycompany.transporteshirata.GUI.Principal;
import com.mycompany.transporteshirata.Datos.ConductoDao;
import com.mycompany.transporteshirata.Logica.Conductor;
import com.mycompany.transporteshirata.Logica.Conductor;
import com.mycompany.transporteshirata.Logica.Camion;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class GuiRegistrarCamion extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiRegistrarCamion
     */
    public GuiRegistrarCamion() {
        initComponents();
        cargarTabla();
        this.setTitle("     Registrar Camión     ");
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (pantalla.width - this.getWidth());
        int y = (pantalla.height - this.getHeight());
        this.setLocation(x / 2 + 150, y / 2 - 40);
        this.setSize(1600, 720);
        cargarCbm();
    }

    public boolean validarPatente(String patente) {
        // Valida formato patente , XX-22-11 O ZZ-XX-22
        return patente.toUpperCase().matches("^([A-Z]{2}-[0-9]{2}-[0-9]{2}|[A-Z]{2}-[A-Z]{2}-[0-9]{2})$");
    }

    public void cargarTabla() {
        String col[] = {"id", "Patente", "Marca", "Modelo", "Año", "Kilometraje", "Conductor"};

        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for (Camion c : dc.listarCamiones()) {

            String infoConductor = "Sin asignar";
            if (c.getConductor() != null && c.getConductor().getIdConductor() != 0) {

                infoConductor = c.getConductor().getNombre();
            }

            Object[] objs = {
                c.getIdCamion(),
                c.getPatente(),
                c.getMarca(),
                c.getModelo(),
                c.getAnio(),
                c.getKilometrajeActual(),
                infoConductor
            };
            tableModel.addRow(objs);
        }
        tbl_camion.setModel(tableModel);

    }

    private void cargarCbm() {
        List<Conductor> lista = cd.listarConductores();
        cmb_conductor.removeAllItems();
        cmb_conductor.addItem("-- Seleccione un conductor --");

        for (Conductor c : lista) {

            cmb_conductor.addItem(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_patente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_anio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_kilometraje = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmb_conductor = new javax.swing.JComboBox<>();
        bt_guardar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_camion = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID");

        txt_id.setEditable(false);

        jLabel2.setText("Patente");

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("Año");

        jLabel6.setText("kilometraje actual");

        jLabel7.setText("km.");

        jLabel8.setText("Conductor");

        bt_guardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_guardar.setText("Guardar");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        bt_editar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_editar.setText("Editar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_cancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_id)
                                    .addComponent(txt_patente)
                                    .addComponent(txt_marca)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_modelo)
                                    .addComponent(txt_anio)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_conductor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_patente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmb_conductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        tbl_camion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_camion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_camionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_camion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        //Validacion campos vacíos
        if (txt_patente.getText().trim().isEmpty() || txt_marca.getText().trim().isEmpty()
                || txt_modelo.getText().trim().isEmpty() || txt_anio.getText().trim().isEmpty()
                || txt_kilometraje.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos del camión.");
            return;
        }
        if (cmb_conductor.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Por favor, asigne un conductor de la lista al camión.");
            return;
        }
        //Validacion formato de Patente
        if (!validarPatente(txt_patente.getText())) {
            JOptionPane.showMessageDialog(this, "Formato de Patente inválido. Use formatos como AB-12-34 o AB-CD-12.");
            return;
        }
        Camion c = new Camion();
        c.setPatente(this.txt_patente.getText());
        c.setMarca(this.txt_marca.getText());
        c.setModelo(this.txt_modelo.getText());
        c.setAnio(Integer.valueOf(this.txt_anio.getText()));
        c.setKilometrajeActual(Integer.valueOf(this.txt_kilometraje.getText()));

        if (cmb_conductor.getSelectedIndex() > 0) {
            Conductor conductorSeleccionado = (Conductor) cmb_conductor.getSelectedItem();
            c.setConductor(conductorSeleccionado);
        } else {

            Conductor vacio = new Conductor();
            vacio.setIdConductor(0);
            c.setConductor(vacio);
        }

        dc.registrarCamion(c);
        cargarTabla();
        JOptionPane.showMessageDialog(this, "✅ Camión guardado exitosamente");
        cambiarAModoNuevo();
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void tbl_camionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_camionMouseClicked
        int selectedRow = this.tbl_camion.getSelectedRow();
        if (selectedRow != -1) {
            Object cellValue = this.tbl_camion.getValueAt(selectedRow, 0);
            Integer id_seleccionado = (Integer) cellValue;
            this.txt_id.setText(id_seleccionado.toString());

            for (Camion c : dc.listarCamiones()) {
                if (c.getIdCamion() == id_seleccionado) {
                    this.txt_patente.setText(c.getPatente());
                    this.txt_marca.setText(c.getMarca());
                    this.txt_modelo.setText(c.getModelo());
                    this.txt_anio.setText(String.valueOf(c.getAnio()));
                    this.txt_kilometraje.setText(String.valueOf(c.getKilometrajeActual()));

                    if (c.getConductor() != null && c.getConductor().getIdConductor() != 0) {

                        for (int i = 1; i < cmb_conductor.getItemCount(); i++) {
                            Conductor itemCombo = (Conductor) cmb_conductor.getItemAt(i);
                            if (itemCombo.getIdConductor() == c.getConductor().getIdConductor()) {
                                cmb_conductor.setSelectedIndex(i);
                                break;
                            }
                        }
                    } else {

                        cmb_conductor.setSelectedIndex(0);
                    }

                }
            }
        }
        cambiarAModoEdicion();
    }//GEN-LAST:event_tbl_camionMouseClicked
    public void cambiarAModoEdicion() {
        this.bt_cancelar.setEnabled(true);
        this.bt_eliminar.setEnabled(true);
        this.bt_editar.setEnabled(true);
        this.bt_guardar.setEnabled(false);

    }

    public void cambiarAModoNuevo() {
        this.bt_cancelar.setEnabled(false);
        this.bt_eliminar.setEnabled(false);
        this.bt_editar.setEnabled(false);
        this.bt_guardar.setEnabled(true);
        limpiarFormulario();
    }

    public void limpiarFormulario() {
        this.txt_id.setText("");
        this.txt_patente.setText("");
        this.txt_modelo.setText("");
        this.txt_marca.setText("");
        this.txt_anio.setText("");
        this.txt_kilometraje.setText("");
    }
    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        cambiarAModoNuevo();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        //Validacion campos vacíos
        if (txt_patente.getText().trim().isEmpty() || txt_marca.getText().trim().isEmpty()
                || txt_modelo.getText().trim().isEmpty() || txt_anio.getText().trim().isEmpty()
                || txt_kilometraje.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos del camión.");
            return;
        }
        if (cmb_conductor.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Por favor, asigne un conductor de la lista al camión.");
            return;
        }
        //Validacion formato de Patente
        if (!validarPatente(txt_patente.getText())) {
            JOptionPane.showMessageDialog(this, "Formato de Patente inválido. Use formatos como AB1234 o ABCD12.");
            return;
        }
        Integer id_seleccionado = Integer.parseInt(this.txt_id.getText());
        System.out.println("ID seleccionado: " + id_seleccionado);

        Camion c_encontrado = null;
        for (Camion c : dc.listarCamiones()) {
            if (c.getIdCamion() == id_seleccionado) {
                c_encontrado = c;
                break;
            }
        }

        if (c_encontrado == null) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
            return;
        }

        c_encontrado.setPatente(this.txt_patente.getText());
        c_encontrado.setMarca(this.txt_marca.getText());
        c_encontrado.setModelo(this.txt_modelo.getText());
        c_encontrado.setAnio(Integer.parseInt(this.txt_anio.getText()));
        c_encontrado.setKilometrajeActual(Integer.parseInt(this.txt_kilometraje.getText()));

        if (!this.txt_id.getText().trim().isEmpty()) {
            c_encontrado.setIdCamion(Integer.parseInt(this.txt_id.getText()));
        }
        if (cmb_conductor.getSelectedIndex() > 0) {
            Conductor conductorSeleccionado = (Conductor) cmb_conductor.getSelectedItem();
            c_encontrado.setConductor(conductorSeleccionado);
        } else {
            Conductor vacio = new Conductor();
            vacio.setIdConductor(0);
            c_encontrado.setConductor(vacio);
        }
        dc.modificarCamion(c_encontrado);

        cargarTabla();
        this.limpiarFormulario();
        cambiarAModoNuevo();
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        Integer id_seleccionado = Integer.parseInt(this.txt_id.getText());
        dc.eliminarCamion(id_seleccionado);
        cambiarAModoNuevo();
        cargarTabla();
        this.limpiarFormulario();
    }//GEN-LAST:event_bt_eliminarActionPerformed
    CamionDao dc = new CamionDao();
    ConductoDao cd = new ConductoDao();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JComboBox<Object> cmb_conductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_camion;
    private javax.swing.JTextField txt_anio;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_kilometraje;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_patente;
    // End of variables declaration//GEN-END:variables

}
