/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.transporteshirata.GUI;

import com.mycompany.transporteshirata.GUI.GuiLoginGeneral;
import javax.swing.JFrame;

/**
 *
 * @author danie
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("     \n     Principal     \n     ");
        if ("conductor".equals(GuiLoginGeneral.cargo_global)) {
            GuiConductor();
        }
        if ("personal".equals(GuiLoginGeneral.cargo_global)) {
            GuiPersonal();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        bt_menu1 = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        openMenuItem1 = new javax.swing.JMenuItem();
        openMenuItem4 = new javax.swing.JMenuItem();
        openMenuItemInventarioPiezas = new javax.swing.JMenuItem();
        openMenuItemPersonal = new javax.swing.JMenuItem();
        bt_menu2 = new javax.swing.JMenu();
        bt_mantenimiento = new javax.swing.JMenuItem();
        bt_mantenimiento2 = new javax.swing.JMenuItem();
        jMenuItemActualizacionSoftware = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemHistorialEquipos = new javax.swing.JMenuItem();
        bt_menu3 = new javax.swing.JMenu();
        bt_mantenimiento1 = new javax.swing.JMenuItem();
        bt_menu4 = new javax.swing.JMenu();
        openMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_menu1.setMnemonic('f');
        bt_menu1.setText("Registro");
        bt_menu1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N

        openMenuItem.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Registrar camion");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        bt_menu1.add(openMenuItem);

        openMenuItem1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        openMenuItem1.setMnemonic('o');
        openMenuItem1.setText("Registrar conductor");
        openMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem1ActionPerformed(evt);
            }
        });
        bt_menu1.add(openMenuItem1);

        openMenuItem4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        openMenuItem4.setMnemonic('o');
        openMenuItem4.setText("Registrar equipo");
        openMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem4ActionPerformed(evt);
            }
        });
        bt_menu1.add(openMenuItem4);

        openMenuItemInventarioPiezas.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        openMenuItemInventarioPiezas.setMnemonic('o');
        openMenuItemInventarioPiezas.setText("Inventario de piezas");
        openMenuItemInventarioPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemInventarioPiezasActionPerformed(evt);
            }
        });
        bt_menu1.add(openMenuItemInventarioPiezas);

        openMenuItemPersonal.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        openMenuItemPersonal.setMnemonic('o');
        openMenuItemPersonal.setText("Registrar personal");
        openMenuItemPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemPersonalActionPerformed(evt);
            }
        });
        bt_menu1.add(openMenuItemPersonal);

        menuBar.add(bt_menu1);

        bt_menu2.setMnemonic('f');
        bt_menu2.setText("Mantenimiento");
        bt_menu2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N

        bt_mantenimiento.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bt_mantenimiento.setMnemonic('o');
        bt_mantenimiento.setText("Hacer mantenimiento camion");
        bt_mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mantenimientoActionPerformed(evt);
            }
        });
        bt_menu2.add(bt_mantenimiento);

        bt_mantenimiento2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bt_mantenimiento2.setMnemonic('o');
        bt_mantenimiento2.setText("Hacer mantenimiento equipo");
        bt_mantenimiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mantenimiento2ActionPerformed(evt);
            }
        });
        bt_menu2.add(bt_mantenimiento2);

        jMenuItemActualizacionSoftware.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenuItemActualizacionSoftware.setText("Actualizar software de equipo");
        jMenuItemActualizacionSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizacionSoftwareActionPerformed(evt);
            }
        });
        bt_menu2.add(jMenuItemActualizacionSoftware);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenuItem1.setText("Historial Mantenimiento");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        bt_menu2.add(jMenuItem1);

        jMenuItemHistorialEquipos.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jMenuItemHistorialEquipos.setText("Historial mantenimiento de equipos");
        jMenuItemHistorialEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistorialEquiposActionPerformed(evt);
            }
        });
        bt_menu2.add(jMenuItemHistorialEquipos);

        menuBar.add(bt_menu2);

        bt_menu3.setMnemonic('f');
        bt_menu3.setText("actualizar_kilometraje");
        bt_menu3.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N

        bt_mantenimiento1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bt_mantenimiento1.setMnemonic('o');
        bt_mantenimiento1.setText("actualizar kilometraje de camion");
        bt_mantenimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mantenimiento1ActionPerformed(evt);
            }
        });
        bt_menu3.add(bt_mantenimiento1);

        menuBar.add(bt_menu3);

        bt_menu4.setMnemonic('f');
        bt_menu4.setText("cerrar sesion");
        bt_menu4.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N

        openMenuItem5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        openMenuItem5.setMnemonic('o');
        openMenuItem5.setText("cerrar sesion");
        openMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem5ActionPerformed(evt);
            }
        });
        bt_menu4.add(openMenuItem5);

        menuBar.add(bt_menu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void GuiConductor() {
        bt_menu1.setEnabled(false);
        bt_menu2.setEnabled(false);
    }
    
    private void GuiPersonal() {
        bt_menu1.setEnabled(false);
        bt_mantenimiento.setEnabled(false);
        jMenuItem1.setEnabled(false);
        jMenuItemHistorialEquipos.setEnabled(false);
        jMenuItemHistorialEquipos.setVisible(false);
        bt_menu3.setEnabled(false);
    }
    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        GuiRegistrarCamion v = new GuiRegistrarCamion();
        desktopPane.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void openMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem1ActionPerformed
        GuiRegistrarConductor c = new GuiRegistrarConductor();
        desktopPane.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_openMenuItem1ActionPerformed

    private void bt_mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mantenimientoActionPerformed
        GuiMantenimiento m = new GuiMantenimiento();
        desktopPane.add(m);
        m.setVisible(true);
    }//GEN-LAST:event_bt_mantenimientoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        GuiHistorialMantenimiento hist = new GuiHistorialMantenimiento();
        desktopPane.add(hist);
        hist.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemHistorialEquiposActionPerformed(java.awt.event.ActionEvent evt) {
        GuiHistorialMantenimientoEquipos histEquipos = new GuiHistorialMantenimientoEquipos();
        desktopPane.add(histEquipos);
        histEquipos.setVisible(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_mantenimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mantenimiento1ActionPerformed
        GuiKilometraje pc = new GuiKilometraje();
        pc.setVisible(true);
        pc.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_bt_mantenimiento1ActionPerformed

    private void openMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem4ActionPerformed
        GuiRegistrarEquipo re = new GuiRegistrarEquipo();
        desktopPane.add(re);
        re.setVisible(true);
    }//GEN-LAST:event_openMenuItem4ActionPerformed

    private void openMenuItemInventarioPiezasActionPerformed(java.awt.event.ActionEvent evt) {
        GuiInventarioPiezas ip = new GuiInventarioPiezas();
        desktopPane.add(ip);
        ip.setVisible(true);
    }

    private void openMenuItemPersonalActionPerformed(java.awt.event.ActionEvent evt) {
        GuiRegistrarPersonal rp = new GuiRegistrarPersonal();
        desktopPane.add(rp);
        rp.setVisible(true);
    }

    private void openMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem5ActionPerformed
        this.setVisible(false);
        GuiLoginGeneral p = new GuiLoginGeneral();
        p.setVisible(true);
    }//GEN-LAST:event_openMenuItem5ActionPerformed

    private void bt_mantenimiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mantenimiento2ActionPerformed
        GuiMantenimientoEquipos me = new GuiMantenimientoEquipos();
        desktopPane.add(me);
        me.setVisible(true);
    }//GEN-LAST:event_bt_mantenimiento2ActionPerformed

    private void jMenuItemActualizacionSoftwareActionPerformed(java.awt.event.ActionEvent evt) {
        GuiActualizacionSoftware as = new GuiActualizacionSoftware();
        desktopPane.add(as);
        as.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bt_mantenimiento;
    private javax.swing.JMenuItem bt_mantenimiento1;
    private javax.swing.JMenuItem bt_mantenimiento2;
    private javax.swing.JMenu bt_menu1;
    private javax.swing.JMenu bt_menu2;
    private javax.swing.JMenu bt_menu3;
    private javax.swing.JMenu bt_menu4;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemActualizacionSoftware;
    private javax.swing.JMenuItem jMenuItemHistorialEquipos;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem openMenuItem1;
    private javax.swing.JMenuItem openMenuItem4;
    private javax.swing.JMenuItem openMenuItem5;
    private javax.swing.JMenuItem openMenuItemInventarioPiezas;
    private javax.swing.JMenuItem openMenuItemPersonal;
    // End of variables declaration//GEN-END:variables

}
